<?php

namespace MoodleImporter;

require_once dirname(__FILE__) . '/../../../application/models/EssayItem.php';
include_once dirname(__FILE__) . '/../../../application/models/XMLUtilities.php';
/**
 * Test class for EssayItem.
 * Generated by PHPUnit on 2012-05-19 at 09:33:30.
 */
class EssayItemTest extends \PHPUnit_Framework_TestCase {

    /**
     * 
     * @covers MoodleImporter\EssayItem::ToXMLElement
     * 
     */
    public function testToXMLElement() 
    {
       $essayItem = new EssayItem;
       $essayItem->Name = "ES 001 - What is";
       $essayItem->PointValue = 2;
       $essayItem->Text = 'What is';
       
       $expected = <<<'ESSAY_XML'
       <question type="essay">
        <name>
         <text><![CDATA[ES 001 - What is]]></text>
        </name> 
        <questiontext format="html">
         <text>What is</text>
        </questiontext>
        <defaultgrade>2</defaultgrade>
       </question>
ESSAY_XML;
       $expected = new \SimpleXMLElement($expected);
       $this->assertTrue(xml_is_equal($expected, $essayItem->ToXMLElement(),false));  
    }

}

?>
