<?php

namespace MoodleImporter;

require_once dirname(__FILE__) . '/../../../application/models/MatchingItem.php';
include_once dirname(__FILE__) . '/../../../application/models/XMLUtilities.php';

/**
 * Test class for MatchingItem.
 * Generated by PHPUnit on 2012-05-19 at 11:48:59.
 */
class MatchingItemTest extends \PHPUnit_Framework_TestCase {

    /**
     * @covers MoodleImporter\MatchingItem::ToXMLElement
     */
    public function testToXMLElement() {
        $matchingItem = new MatchingItem;
        $matchingItem->Name = "MT 001 - What is";
        $matchingItem->PointValue = 2;
        $matchingItem->Text = 'What is';
        $matchingItem->Options = array('Option 1' => 'Definition 1', 'Option 2' => 'Definition 2');
       
        $expected = <<<'MATCHING_XML'
        <question type="matching">
        <name>
            <text>MT 001 - What is</text>
        </name> 
        <defaultgrade>
            2
        </defaultgrade>
        <subquestion>
            <text>
                Option 1
            </text>
            <answer>
                Definition 1
            </answer>
        </subquestion>
        <subquestion>
            <text>
                Option 2
            </text>
            <answer>
                Definition 2
            </answer>
        </subquestion>

        </question>
MATCHING_XML;
        $expected = new \SimpleXMLElement($expected);
        $this->assertTrue(xml_is_equal($expected, $matchingItem->ToXMLElement(),false)); 
    }
}

?>
