<?php

namespace MoodleImporter;

require_once dirname(__FILE__) . '/../../../application/models/MultipleChoiceOption.php';

/**
 * Test class for MultipleChoiceOption.
 * Generated by PHPUnit on 2012-05-20 at 08:13:31.
 */
class MultipleChoiceOptionTest extends \PHPUnit_Framework_TestCase {

   
    /**
     * @covers MoodleImporter\MultipleChoiceOption::ToXMLElement
     */
    public function testToXMLElement() 
    {
        $multipleChoiceOption = new MultipleChoiceOption;
        $multipleChoiceOption->Text = "Alabama";
        $multipleChoiceOption->Value = 100;
        $expected = <<<OPTION_XML
        <answer fraction="100">
            <text>Alabama</text>
        </answer>
OPTION_XML;
        
        $this->assertTrue(xml_is_equal($multipleChoiceOption->ToXMLElement(), new \SimpleXMLElement($expected)));
    }

}

?>
