<?php

namespace MoodleImporter;

require_once dirname(__FILE__) . '/../../../application/models/MultipleChoiceItem.php';

/**
 * Test class for MultipleChoiceItem.
 * Generated by PHPUnit on 2012-05-20 at 14:33:56.
 */
class MultipleChoiceItemTest extends \PHPUnit_Framework_TestCase {

    /**
     * @covers MoodleImporter\MultipleChoiceItem::ToXMLElement
     * @todo Implement testToXMLElement().
     */
    public function testToXMLElement() 
    {
        $multipleChoiceItem = new MultipleChoiceItem;
        $multipleChoiceItem->Name = "MC 001 - What is";
        $multipleChoiceItem->PointValue = 2;
        $multipleChoiceItem->ShuffleAnswers = true;
        $multipleChoiceItem->Text = "What is the answer to this question?";
        $multipleChoiceItem->SingleSelection = true;
        $multipleChoiceItem->AnswerNumbering = "abc";
        
        $option1 = new MultipleChoiceOption;
        $option1->Text = "The correct answer";
        $option1->Value = 100;
        
        $option2 = new MultipleChoiceOption;
        $option2->Text = "A distractor";
        $option2->Value = 0;
        
        $option3 = new MultipleChoiceOption;
        $option3->Text = "Another distractor";
        $option3->Value = 0;

        $multipleChoiceItem->Options = array($option1, $option2, $option3);
        
        $expected = <<<'MC_XML'
        <question type="multichoice">
            <name>
                <text>MC 001 - What is</text>
            </name>
            <questiontext format="html">
                <text><![CDATA[What is the answer to this question?]]></text>
            </questiontext>
            <answer fraction="100">
               <text>The correct answer</text>
            </answer>
            <answer fraction="0">
                <text>A distractor</text>
            </answer>
            <answer fraction="0">
                <text>Another distractor</text>
            </answer>
            <shuffleanswers>1</shuffleanswers>
            <single>true</single>
            <answernumbering>abc</answernumbering>
        </question>
MC_XML;
        
        $this->assertTrue(xml_is_equal(new \SimpleXMLElement($expected), $multipleChoiceItem->ToXMLElement()));
    }

}

?>
