<?php

namespace MoodleImporter;

require_once dirname(__FILE__) . '/../../../application/models/Quiz.php';
include_once dirname(__FILE__) . '/../../../application/models/XMLUtilities.php';

/**
 * Test class for Quiz.
 * Generated by PHPUnit on 2012-05-18 at 22:10:42.
 */
class QuizTest extends \PHPUnit_Framework_TestCase {

    /**
     * @covers MoodleImporter\Quiz::ToXMLString
     */
    public function testToXMLString() {
        $quiz = new Quiz;
        $quiz->Category = "Quiz #1";
        $output = <<<'QUIZ_TEST'
        <quiz>
            <question type="category">
                <category>
                    <text>$course$/Quiz #1</text>
                </category>
            </question>
        </quiz>
QUIZ_TEST;
        
        $this->assertTrue(xml_is_equal(new \SimpleXMLElement($output), new \SimpleXMLElement($quiz->ToXMLString())));
    }
    
    /**
     * @covers MoodleImporter\Quiz::ToXMLString 
     */
    public function testToXMLStringEssayItem() {
        $essayItem = new EssayItem;
        $essayItem->Name = "ES 001 - What is";
        $essayItem->Text = "What is";
        $essayItem->PointValue = 2;
        $quiz = new Quiz;
        $quiz->Category = "Quiz #1";
        $quiz->Items[] = $essayItem;
        $output = <<<'QUIZ_TEST'
        <quiz>
            <question type="category">
                <category>
                    <text>$course$/Quiz #1</text>
                </category>
            </question>
            <question type="essay">
                <name>
                    <text>ES 001 - What is</text>
                </name>
                <questiontext format="html">
                    <text><![CDATA[What is]]></text>
                </questiontext>
                <defaultgrade>2</defaultgrade>
            </question>
        </quiz>
QUIZ_TEST;
        
        $this->assertTrue(xml_is_equal(new \SimpleXMLElement($output), new \SimpleXMLElement($quiz->ToXMLString())));
    }
}

?>
